// ── Deutsch (de) mascot pack ──
//
// Transcreated, not translated: the crab is the same lazy, sarcastic,
// scandalous creature in every language, but the jokes are local ones.
// See en.ts for the contract every pack has to satisfy.
//
// Model-drafted, machine-checked against the contract — the wording is
// still worth a native speaker's pass.

import type { MascotPhraseSet } from "@/lib/mascot-phrases";

export const de: MascotPhraseSet = {
  sass: [
    "Ich mache hier die ganze Arbeit.",
    "Schneller deployen, Menschen.",
    "Bug? Nein, ein Feature. 🫡",
    "Ich brauche mehr Gehalt.",
    "*kippt den Tisch*",
    "sudo mach mir ein Brot",
    "404: Motivation nicht gefunden",
    "Deploy am Freitag? Trau dich.",
  ],
  idle: [
    "🫥",
    "🧐",
    "⏳",
    "*starrt ins Leere*",
    "*Fahrstuhlmusik*",
    "hmmm...",
    "*existiert nachdrücklich*",
    "*blinzelt langsam*",
    "*tut so, als würde er arbeiten*",
    "*zählt Pixel*",
    "*lädt Persönlichkeit...*",
    "*wartet auf irgendwas*",
  ],
  sleep: [
    "💤 gute Nacht",
    "😴 schnarch...",
    "💤 noch 5 Minuten...",
    "*schnarcht leise*",
    "😴 weck mich nächste Woche...",
    "💤 ich ruhe nur die Augen aus...",
  ],
  jump: [
    "HOPP!",
    "🦘 Sprung!",
    "Parkour, aber seitwärts.",
    "Bis zur Unendlichkeit!",
    "🚀 JUHUUU!",
    "Ich kann fliegen!",
  ],
  dance: [
    "💃🕺 Tanzfläche frei!",
    "♪ tsching bumm ♪",
    "🎶 los geht’s!",
    "🪩 DISCO-MODUS!",
    "*macht den Roboter*",
    "♪ dum dum dum ♪",
  ],
  facepalm: [
    "🤦 na super.",
    "Im Ernst?",
    "Warum nur.",
    "*tief durchatmen*",
    "Mir fehlen die Worte...",
    "Dieser Tag ist abgesagt.",
  ],
  nameGreetings: [
    "Hallo {name}! 👋",
    "Hey {name} 🦀",
    "{name}, aufwachen!",
    "Pssst, {name}...",
    "{name}, deploy das Ding! 🚀",
    "Kaffee, {name}?",
    "Aufstehen, {name}!",
    "{name}, alles gut? 👀",
    "{name}! Lange nicht gekrabbelt.",
    "{name}, hör auf zu scrollen 😤",
    "{name}, die Box grüßt 📦",
    "*winkt {name} zu*",
    "{name}, Snack? 🥨",
    "{name}, du bist top 💜",
    "Moin {name}!",
    "{name}, bau was Cooles",
    "Schon gegessen, {name}? 🍱",
    "{name}, ich hab dich vermisst 🥺",
    "*stupst {name} an*",
    "{name}, der Server läuft 🛡️",
  ],
  nameFallbacks: [
    "Chef",
    "Kapitän",
    "Freund",
    "Mensch",
    "Partner",
    "Kumpel",
    "Meister",
    "Kollege",
  ],
  power: [
    "⚡ UNBEGRENZTE MACHT!",
    "🔥 SUPER-SCHERE!",
    "💪 MAXIMALE KRAFT!",
    "⚡ ICH BIN DIE BOX!",
    "🦀👑 KÖNIGSKRABBE!",
    "✨ LEVEL AUFGESTIEGEN!",
    "🔱 DAS IST MEIN THRON!",
    "⚡ WER IST DER CHEF?!",
    "👑 VERNEIGT EUCH!",
    "🦀 KRABBEN AN DIE MACHT!",
    "⚡ ULTRA-INSTINKT!",
    "💎 DIAMANTSCHEREN AKTIV!",
    "🔥 FEUER UND FLAMME!",
    "⚡ ÜBER DAS LIMIT HINAUS!",
    "🦀 KÖNIG DES DASHBOARDS!",
    "☢️ RAKETENSTART ERKANNT!",
    "👑 HERRSCHER ALLER BOXEN!",
    "⚡ ENDFORM ERREICHT!",
    "🔱 POSEIDON-MODUS!",
    "💪 DAFÜR HABE ICH TRAINIERT!",
  ],
};

