// Locale: nl (Nederlands) — mascot phrase pack, transcreated (not translated).
// model-drafted — needs native review · 2026-08-21

import type { MascotPhraseSet } from '@/lib/mascot-phrases'

export const nl: MascotPhraseSet = {
  sass: [
    'Ik doe hier al het werk. 🦀',
    'Sneller deployen, mensen.',
    'Bug? Nee hoor, een feature. 🫡',
    'Ik wil opslag.',
    '*gooit de tafel om*',
    'sudo maak een boterham voor mij',
    '404: motivatie niet gevonden',
    'Op vrijdag deployen? Durf eens.',
  ],
  idle: [
    '😶',
    '🌧️',
    '🧀',
    '*staart in het niets*',
    '*liftmuziek*',
    'tja...',
    '*bestaat nadrukkelijk*',
    '*knippert traag*',
    '*doet alsof hij werkt*',
    '*telt pixels*',
    '*persoonlijkheid laden...*',
    '*wacht op iets spannends*',
  ],
  sleep: [
    '💤 welterusten',
    '😴 zzz... 🌊',
    '💤 nog vijf minuutjes...',
    '*snurkt zachtjes*',
    '😴 wek me in de herfst...',
    '💤 ik rust alleen mijn ogen...',
  ],
  jump: [
    'HOPSA!',
    '🦘 sprong!',
    'Parkour, maar dan zijwaarts.',
    'Naar de oneindigheid!',
    '🚀 JOEHOEE!',
    'Ik kan vliegen!',
  ],
  dance: [
    '💃🕺 dansen maar!',
    '♪ tsjing boem ♪',
    '🎶 kom op!',
    '🪩 DISCOSTAND AAN!',
    '*doet de robot*',
    '♪ doef doef doef ♪',
  ],
  facepalm: [
    '🤦 ach jeetje.',
    'Serieus?',
    'Waarom toch.',
    '*haalt diep adem*',
    'Ik heb geen woorden...',
    'Deze dag is geannuleerd.',
  ],
  nameGreetings: [
    'Hoi {name}! 👋',
    'Heej {name} 🦀',
    '{name}, wakker worden!',
    'psst {name}, kijk eens...',
    '{name}, ga deployen! 🚀',
    'Koffie, {name}?',
    'Opstaan, {name}!',
    '{name}, gaat het? 👀',
    '{name}! Lang niet gezien.',
    '{name}, stop met scrollen 😤',
    '{name}, de box groet je 📦',
    '*zwaait naar {name}*',
    '{name}, een stroopwafel? 🍪',
    '{name}, jij bent top 💜',
    'Yo {name}, alles goed?',
    '{name}, maak iets moois',
    'Al gegeten, {name}? 🍱',
    '{name}, ik miste je 🥺',
    '*port {name} zachtjes*',
    '{name}, de server draait door 🛡️',
  ],
  nameFallbacks: [
    'baas',
    'kapitein',
    'vriend',
    'mens',
    'maatje',
    'kameraad',
    'kanjer',
    'held',
  ],
  power: [
    '⚡ ONBEPERKTE KRACHT!',
    '🔥 SUPERSCHAAR!',
    '💪 MAXIMAAL VERMOGEN!',
    '⚡ IK BEN DE BOX!',
    '🦀👑 KONINGSKRAB!',
    '✨ LEVEL OMHOOG!',
    '🔱 DIT IS MIJN TROON!',
    '⚡ WIE IS DE BAAS?!',
    '👑 BUIG VOOR MIJ!',
    '🦀 KRABBEN AAN DE MACHT!',
    '⚡ ULTRA-INSTINCT!',
    '💎 DIAMANTEN SCHAREN!',
    '🔥 VUUR EN VLAM!',
    '⚡ VOORBIJ DE GRENS!',
    '🦀 KONING VAN HET DASHBOARD!',
    '☢️ LANCERING GEDETECTEERD!',
    '👑 HEERSER OVER ALLE BOXEN!',
    '⚡ EINDVORM BEREIKT!',
    '🔱 POSEIDON-STAND!',
    '💪 HIERVOOR HEB IK GETRAIND!',
  ],
}
