// Locale: sv (Svenska) — mascot phrase pack, transcreated (not translated).
// model-drafted — needs native review · 2026-08-21

import type { MascotPhraseSet } from '@/lib/mascot-phrases'

export const sv: MascotPhraseSet = {
  sass: [
    'Jag gör allt jobb här. 🦀',
    'Snabbare deploy, människor.',
    'Bug? Nej, en funktion. 🫡',
    'Jag vill ha löneförhöjning.',
    '*välter bordet*',
    'sudo gör en macka åt mig',
    '404: motivation hittades inte',
    'Deploy på en fredag? Vågar du?',
  ],
  idle: [
    '😌',
    '❄️',
    '☕',
    '*stirrar ut i tomma intet*',
    '*hissmusik*',
    'nja...',
    '*existerar med eftertryck*',
    '*blinkar långsamt*',
    '*låtsas jobba*',
    '*räknar pixlar*',
    '*laddar personlighet...*',
    '*väntar på något spännande*',
  ],
  sleep: [
    '💤 god natt',
    '😴 zzz... ⚓',
    '💤 fem minuter till...',
    '*snarkar tyst*',
    '😴 väck mig till våren...',
    '💤 jag vilar bara ögonen...',
  ],
  jump: [
    'HOPPSAN!',
    '🦘 hopp!',
    'Parkour, fast i sidled.',
    'Mot oändligheten!',
    '🚀 JIHAAA!',
    'Jag kan flyga!',
  ],
  dance: [
    '💃🕺 dags att dansa!',
    '♪ tjoho ♪',
    '🎶 kör hårt!',
    '🪩 DISKOLÄGE PÅ!',
    '*gör roboten*',
    '♪ dunk dunk dunk ♪',
  ],
  facepalm: [
    '🤦 oj då.',
    'Allvarligt?',
    'Varför då.',
    '*andas djupt*',
    'Jag har inga ord...',
    'Dagen är inställd.',
  ],
  nameGreetings: [
    'Hej {name}! 👋',
    'Tjena {name} 🦀',
    '{name}, vakna!',
    'psst {name}, kolla här...',
    '{name}, kör en deploy! 🚀',
    'Kaffe, {name}?',
    'Upp med dig, {name}!',
    '{name}, allt bra? 👀',
    '{name}! Länge sedan sist.',
    '{name}, sluta scrolla 😤',
    '{name}, lådan hälsar 📦',
    '*vinkar till {name}*',
    '{name}, en kanelbulle? 🧁',
    '{name}, du är bäst 💜',
    'Tjabba {name}!',
    '{name}, bygg något fint',
    'Har du ätit, {name}? 🍱',
    '{name}, jag har saknat dig 🥺',
    '*puttar lite på {name}*',
    '{name}, servern snurrar på 🛡️',
  ],
  nameFallbacks: [
    'chefen',
    'kapten',
    'vän',
    'människa',
    'kompis',
    'polare',
    'mästare',
    'stjärna',
  ],
  power: [
    '⚡ OBEGRÄNSAD KRAFT!',
    '🔥 SUPERKLO!',
    '💪 MAXIMAL STYRKA!',
    '⚡ JAG ÄR LÅDAN!',
    '🦀👑 KUNGSKRABBA!',
    '✨ NY NIVÅ!',
    '🔱 DETTA ÄR MIN TRON!',
    '⚡ VEM BESTÄMMER HÄR?!',
    '👑 BUGA FÖR MIG!',
    '🦀 KRABBOR TILL MAKTEN!',
    '⚡ ULTRA INSTINKT!',
    '💎 DIAMANTKLOR AKTIVERADE!',
    '🔥 ELD OCH LÅGOR!',
    '⚡ BORTOM ALLA GRÄNSER!',
    '🦀 KUNG ÖVER INSTRUMENTPANELEN!',
    '☢️ UPPSKJUTNING UPPTÄCKT!',
    '👑 HÄRSKARE ÖVER ALLA LÅDOR!',
    '⚡ SLUTFORM UPPNÅDD!',
    '🔱 POSEIDONLÄGE!',
    '💪 JAG HAR TRÄNAT FÖR DETTA!',
  ],
}
