/**
 * ClawKeep TS bridge — drives the Python `clawkeepd` daemon and reads/writes
 * the same state files (config.toml, token, state.json).
 *
 * Pairing lives in:
 *   src/lib/clawkeep-connect.ts
 *   src/app/setup-api/clawkeep/pair/{start,callback,status}/route.ts
 * Mirrors the existing ClawAI pair flow (clawai-connect / clawai/start /
 * clawai/callback / clawai/status) so the two device-pair flows stay in
 * lockstep.
 *
 * Data layout (under $CLAWKEEP_DATA_DIR, default `~/.clawkeep`):
 *   token        — `claw_*` portal token, mode 0600
 *   repo-pass    — restic repo password, mode 0600
 *   state.json   — last-run summary surfaced to the UI
 *   config.toml  — paths/excludes/schedule (user-editable from UI)
 *   pair-state.json — in-flight pairing session, written by clawkeep-connect
 */

import { spawn } from "node:child_process";
import { promises as fs } from "node:fs";
import os from "node:os";
import path from "node:path";

export const CLAWKEEP_DATA_DIR =
  process.env.CLAWKEEP_DATA_DIR?.trim() || path.join(os.homedir(), ".clawkeep");
export const CLAWKEEP_CONFIG_PATH =
  process.env.CLAWKEEP_CONFIG_PATH?.trim() || path.join(CLAWKEEP_DATA_DIR, "config.toml");

const TOKEN_PATH = path.join(CLAWKEEP_DATA_DIR, "token");
const STATE_PATH = path.join(CLAWKEEP_DATA_DIR, "state.json");

export const DEFAULT_PORTAL_SERVER =
  process.env.CLAWKEEP_PORTAL_SERVER?.trim() || "https://openclawhardware.dev";

const DEFAULT_BIN_NAME = "clawkeepd";

const DEFAULT_CONFIG_TOML = `# /home/clawbox/.clawkeep/config.toml
# Generated by ClawKeep on first run. Edit from the desktop app or by hand.

server = "${DEFAULT_PORTAL_SERVER}"

paths = [
    "/home/clawbox/clawbox/data",
]

exclude = [
    "**/node_modules",
    "**/.cache",
    "**/.venv",
    "**/__pycache__",
    "*.tmp",
    "*.log",
]

schedule = "daily"

[restic]
binary = "/usr/bin/restic"
compression = "auto"
read_concurrency = 2

[heartbeat]
idle_interval_hours = 24
`;

export interface ClawKeepStatus {
  paired: boolean;
  configured: boolean;
  configPath: string;
  server: string;
  paths: string[];
  exclude: string[];
  schedule: string;
  lastBackupAtMs: number;
  lastHeartbeatAtMs: number;
  lastHeartbeatStatus: string;
  cloudBytes: number;
  snapshotCount: number;
  resticInstalled: boolean;
  daemonInstalled: boolean;
}

export class ClawKeepError extends Error {
  constructor(
    message: string,
    readonly status: number = 500,
  ) {
    super(message);
    this.name = "ClawKeepError";
  }
}

// ────────────────────────────────────────────────────────────────────
// File helpers
// ────────────────────────────────────────────────────────────────────

async function ensureDataDir(): Promise<void> {
  await fs.mkdir(CLAWKEEP_DATA_DIR, { recursive: true, mode: 0o700 });
}

async function writeSecret(p: string, contents: string): Promise<void> {
  await ensureDataDir();
  // Atomic-rename a 0600 tmp file so the secret is never world-readable
  // even on a crash mid-write.
  const tmp = `${p}.tmp`;
  const handle = await fs.open(tmp, "w", 0o600);
  try {
    await handle.writeFile(contents, "utf8");
  } finally {
    await handle.close();
  }
  await fs.chmod(tmp, 0o600);
  await fs.rename(tmp, p);
}

// ────────────────────────────────────────────────────────────────────
// Token / config / state
// ────────────────────────────────────────────────────────────────────

export async function readToken(): Promise<string | null> {
  try {
    const raw = (await fs.readFile(TOKEN_PATH, "utf8")).trim();
    if (!raw.startsWith("claw_")) return null;
    return raw;
  } catch (e) {
    if ((e as NodeJS.ErrnoException).code === "ENOENT") return null;
    throw e;
  }
}

export async function writeToken(token: string): Promise<void> {
  if (!token.startsWith("claw_")) {
    throw new ClawKeepError("refusing to write non-claw_* token", 400);
  }
  await writeSecret(TOKEN_PATH, token);
}

export async function deleteToken(): Promise<void> {
  await fs.unlink(TOKEN_PATH).catch((e) => {
    if ((e as NodeJS.ErrnoException).code !== "ENOENT") throw e;
  });
}

export async function readConfigToml(): Promise<string> {
  try {
    return await fs.readFile(CLAWKEEP_CONFIG_PATH, "utf8");
  } catch (e) {
    if ((e as NodeJS.ErrnoException).code !== "ENOENT") throw e;
  }
  // Race-safe seed: O_CREAT|O_EXCL means concurrent first-run callers
  // can't double-write; whichever loses gets EEXIST and reads the winner's
  // content on the next pass.
  await ensureDataDir();
  try {
    const handle = await fs.open(CLAWKEEP_CONFIG_PATH, "wx", 0o644);
    try {
      await handle.writeFile(DEFAULT_CONFIG_TOML, "utf8");
    } finally {
      await handle.close();
    }
  } catch (e) {
    if ((e as NodeJS.ErrnoException).code !== "EEXIST") throw e;
  }
  return fs.readFile(CLAWKEEP_CONFIG_PATH, "utf8");
}

export async function writeConfigToml(toml: string): Promise<void> {
  await ensureDataDir();
  await fs.writeFile(CLAWKEEP_CONFIG_PATH, toml, { mode: 0o644 });
}

interface StateFile {
  last_heartbeat_at_ms?: number;
  last_heartbeat_status?: string;
  last_backup_at_ms?: number;
  last_cloud_bytes?: number;
  last_snapshot_count?: number;
}

interface ParsedConfigBits {
  server: string;
  paths: string[];
  exclude: string[];
  schedule: string;
}

/** Tiny TOML reader covering only the four scalars/arrays the status
 * panel needs. The daemon does the strict parse; pulling in a full TOML
 * dep just to display paths in a sidebar is overkill. */
export function parseConfigBits(toml: string): ParsedConfigBits {
  const out: ParsedConfigBits = {
    server: DEFAULT_PORTAL_SERVER,
    paths: [],
    exclude: [],
    schedule: "daily",
  };
  const lines = toml.split(/\r?\n/);
  let inSection = "";
  let pendingArray: { bucket: "paths" | "exclude" } | null = null;
  let pendingItems: string[] = [];

  for (const raw of lines) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;

    if (line.startsWith("[")) {
      if (pendingArray) {
        out[pendingArray.bucket] = pendingItems;
        pendingArray = null;
        pendingItems = [];
      }
      inSection = line.replace(/^\[+|\]+$/g, "");
      continue;
    }

    if (pendingArray) {
      const items = line.match(/"([^"]*)"/g) || [];
      for (const it of items) pendingItems.push(it.slice(1, -1));
      if (line.includes("]")) {
        out[pendingArray.bucket] = pendingItems;
        pendingArray = null;
        pendingItems = [];
      }
      continue;
    }

    if (inSection !== "") continue;

    const eq = line.indexOf("=");
    if (eq < 0) continue;
    const key = line.slice(0, eq).trim();
    const value = line.slice(eq + 1).trim();

    if (key === "server") {
      const m = value.match(/^"([^"]*)"/);
      if (m) out.server = m[1];
    } else if (key === "schedule") {
      const m = value.match(/^"([^"]*)"/);
      if (m) out.schedule = m[1];
    } else if (key === "paths" || key === "exclude") {
      const inline = value.match(/^\[(.*)\]$/);
      if (inline) {
        const items = inline[1].match(/"([^"]*)"/g) || [];
        out[key] = items.map((s) => s.slice(1, -1));
      } else if (value.startsWith("[")) {
        pendingArray = { bucket: key };
        pendingItems = [];
        const tail = value.slice(1);
        const items = tail.match(/"([^"]*)"/g) || [];
        for (const it of items) pendingItems.push(it.slice(1, -1));
        if (tail.includes("]")) {
          out[pendingArray.bucket] = pendingItems;
          pendingArray = null;
          pendingItems = [];
        }
      }
    }
  }
  return out;
}

async function readStateFile(): Promise<StateFile> {
  try {
    return JSON.parse(await fs.readFile(STATE_PATH, "utf8")) as StateFile;
  } catch {
    return {};
  }
}

// ────────────────────────────────────────────────────────────────────
// Binary discovery (memoised)
// ────────────────────────────────────────────────────────────────────

function which(bin: string): Promise<boolean> {
  return new Promise((resolve) => {
    const p = spawn("which", [bin], { stdio: "ignore" });
    p.on("error", () => resolve(false));
    p.on("close", (code) => resolve(code === 0));
  });
}

// systemd's secure_path doesn't include ~/.local/bin, so a pip --user install
// of clawkeepd isn't on PATH for the Next.js process. Cache *successful*
// lookups for the process lifetime — a positive answer doesn't change without
// a restart. Failures aren't cached so a freshly-installed `apt install
// restic` or `pip install --user .` flips the status panel from "Setup
// needed" to "Ready" on the next poll without restarting clawbox-setup.
let resticInstalledCache: boolean | null = null;
let daemonBinCache: string | null = null;

async function getResticInstalled(): Promise<boolean> {
  if (resticInstalledCache === true) return true;
  const ok = await which("restic");
  if (ok) resticInstalledCache = true;
  return ok;
}

async function getDaemonBin(): Promise<string | null> {
  if (daemonBinCache) return daemonBinCache;
  const override = process.env.CLAWKEEP_BIN?.trim();
  if (override) {
    daemonBinCache = override;
    return override;
  }
  if (await which(DEFAULT_BIN_NAME)) {
    daemonBinCache = DEFAULT_BIN_NAME;
    return DEFAULT_BIN_NAME;
  }
  const fallback = path.join(os.homedir(), ".local", "bin", DEFAULT_BIN_NAME);
  try {
    await fs.access(fallback);
    daemonBinCache = fallback;
    return fallback;
  } catch {
    return null;
  }
}

// ────────────────────────────────────────────────────────────────────
// Status
// ────────────────────────────────────────────────────────────────────

export async function getStatus(): Promise<ClawKeepStatus> {
  await ensureDataDir();
  const [token, configToml, stateRaw, resticInstalled, daemonBin] = await Promise.all([
    readToken(),
    readConfigToml(),
    readStateFile(),
    getResticInstalled(),
    getDaemonBin(),
  ]);

  const bits = parseConfigBits(configToml);
  return {
    paired: !!token,
    configured: bits.paths.length > 0,
    configPath: CLAWKEEP_CONFIG_PATH,
    server: bits.server,
    paths: bits.paths,
    exclude: bits.exclude,
    schedule: bits.schedule,
    lastBackupAtMs: stateRaw.last_backup_at_ms ?? 0,
    lastHeartbeatAtMs: stateRaw.last_heartbeat_at_ms ?? 0,
    lastHeartbeatStatus: stateRaw.last_heartbeat_status ?? "",
    cloudBytes: stateRaw.last_cloud_bytes ?? 0,
    snapshotCount: stateRaw.last_snapshot_count ?? 0,
    resticInstalled,
    daemonInstalled: daemonBin !== null,
  };
}

// ────────────────────────────────────────────────────────────────────
// Backup runs — spawn `clawkeepd --once` (or --idle)
// ────────────────────────────────────────────────────────────────────

export interface BackupResult {
  exitCode: number;
  stdout: string;
  stderr: string;
}

// Cap stdout/stderr capture so a 4-hour restic run on a chatty TTY can't
// OOM the Next.js process. We only show a 2 KB tail in the UI anyway, so
// keeping a generous tail buffer (64 KB) leaves plenty of room for the
// final summary line + any stderr trace while staying bounded.
const MAX_OUTPUT_BYTES = 64 * 1024;

function appendCapped(prev: string, chunk: string): string {
  const next = prev + chunk;
  if (next.length <= MAX_OUTPUT_BYTES) return next;
  return next.slice(next.length - MAX_OUTPUT_BYTES);
}

export async function runBackup(opts: { idle?: boolean } = {}): Promise<BackupResult> {
  const bin = (await getDaemonBin()) ?? DEFAULT_BIN_NAME;
  return new Promise((resolve) => {
    const env = { ...process.env, CLAWKEEP_DATA_DIR };
    const args = ["--config", CLAWKEEP_CONFIG_PATH];
    if (opts.idle) args.push("--idle");
    const child = spawn(bin, args, { env, stdio: ["ignore", "pipe", "pipe"] });
    let stdout = "";
    let stderr = "";
    child.stdout.on("data", (b: Buffer) => {
      stdout = appendCapped(stdout, b.toString("utf8"));
    });
    child.stderr.on("data", (b: Buffer) => {
      stderr = appendCapped(stderr, b.toString("utf8"));
    });
    child.on("error", (e) => {
      // ENOENT etc. — synthesize a non-zero exit so callers can surface it.
      resolve({ exitCode: 127, stdout, stderr: appendCapped(stderr, e.message) });
    });
    child.on("close", (code) => {
      resolve({ exitCode: code ?? -1, stdout, stderr });
    });
  });
}
