/**
 * ClawKeep TS bridge — drives the Python `clawkeepd` daemon and reads/writes
 * the same state files (config.toml, token, state.json).
 *
 * Pairing lives in:
 *   src/lib/clawkeep-connect.ts
 *   src/app/setup-api/clawkeep/pair/{start,callback,status}/route.ts
 * Mirrors the existing ClawAI pair flow (clawai-connect / clawai/start /
 * clawai/callback / clawai/status) so the two device-pair flows stay in
 * lockstep.
 *
 * Data layout (under $CLAWKEEP_DATA_DIR, default `~/.clawkeep`):
 *   token        — `claw_*` portal token, mode 0600
 *   state.json   — last-run summary surfaced to the UI
 *   config.toml  — schedule + openclaw flags (user-editable from UI)
 *   pair-state.json — in-flight pairing session, written by clawkeep-connect
 */

import { spawn } from "node:child_process";
import { randomBytes } from "node:crypto";
import { constants as fsConstants, promises as fs } from "node:fs";
import os from "node:os";
import path from "node:path";
import { StringDecoder } from "node:string_decoder";

import { findOpenclawBin } from "@/lib/openclaw-config";
import { getEdition } from "@/lib/harness";
import { backupSourceFor } from "@/lib/harness/backup-source";
import type { HarnessId } from "@/lib/harness/transport";

export const CLAWKEEP_DATA_DIR =
  process.env.CLAWKEEP_DATA_DIR?.trim() || path.join(os.homedir(), ".clawkeep");
export const CLAWKEEP_CONFIG_PATH =
  process.env.CLAWKEEP_CONFIG_PATH?.trim() || path.join(CLAWKEEP_DATA_DIR, "config.toml");

const TOKEN_PATH = path.join(CLAWKEEP_DATA_DIR, "token");
const PASSPHRASE_PATH = path.join(CLAWKEEP_DATA_DIR, "passphrase");
const STATE_PATH = path.join(CLAWKEEP_DATA_DIR, "state.json");
// Marker that a restore is in flight. The restore handler creates it
// before invoking the Python CLI and removes it when done so the shelf
// shield can pulse orange while it runs. Stamped with the start time so
// crashes don't leave the shield pulsing forever.
const RESTORING_FLAG_PATH = path.join(CLAWKEEP_DATA_DIR, "restoring.flag");
const SCHEDULE_PATH = path.join(CLAWKEEP_DATA_DIR, "schedule.json");

export const DEFAULT_PORTAL_SERVER =
  process.env.CLAWKEEP_PORTAL_SERVER?.trim() || "https://clawbox.com";

const DEFAULT_BIN_NAME = "clawkeepd";

const DEFAULT_CONFIG_TOML = `# /home/clawbox/.clawkeep/config.toml
# Generated by ClawKeep on first run. Edit from the desktop app or by hand.

server = "${DEFAULT_PORTAL_SERVER}"

schedule = "daily"

# clawkeep delegates "what to back up" to \`openclaw backup create\` —
# it captures OpenClaw state, config, credentials, sessions, and
# (optionally) workspaces. See https://docs.openclaw.ai/cli/backup.
[openclaw]
binary = "openclaw"
include_workspace = true
only_config = false
verify = true
output_dir = ""

[heartbeat]
idle_interval_hours = 24
`;

// Daemon heartbeat status values, mirrored from clawkeep/clawkeep/state.py.
// Typed so callers reading `lastHeartbeatStatus` get an enum-like surface
// without us having to ship a runtime constant into the client bundle
// (clawkeep.ts uses node:fs and isn't safe to import from a client file).
//
// "needs-passphrase" is the daemon's signal that encryption is mandatory
// but no passphrase is set on the device — the UI shows a "Set passphrase"
// modal in response and re-runs the backup once the user supplies one.
export type HeartbeatStatus = "" | "running" | "ok" | "error" | "idle" | "needs-passphrase";

export type ScheduleFrequency = "daily" | "weekly";

export interface ClawKeepSchedule {
  enabled: boolean;
  frequency: ScheduleFrequency;
  /** "HH:MM" 24-hour, device-local time. */
  timeOfDay: string;
  /** 0=Sunday … 6=Saturday. Only used when frequency === "weekly". */
  weekday: number;
  /** Auto-cleanup: keep the newest N *unlocked* snapshots after each
   * successful backup. Locked snapshots are always kept and never counted
   * toward N. 0 disables retention. Read by the device runner from
   * schedule.json. */
  retentionKeepLast: number;
}

/** Default retention window. Keep the last 10 unlocked snapshots. */
export const DEFAULT_RETENTION_KEEP_LAST = 10;

export const DEFAULT_SCHEDULE: ClawKeepSchedule = {
  enabled: false,
  frequency: "daily",
  timeOfDay: "02:00",
  weekday: 0,
  retentionKeepLast: DEFAULT_RETENTION_KEEP_LAST,
};

export interface ClawKeepStatus {
  paired: boolean;
  configured: boolean;
  server: string;
  lastBackupAtMs: number;
  lastHeartbeatAtMs: number;
  lastHeartbeatStatus: HeartbeatStatus;
  /** Sub-phase during an in-flight backup; empty when nothing is running. */
  currentStep: string;
  /** When the daemon entered its current step (unix ms). */
  currentStepAtMs: number;
  cloudBytes: number;
  snapshotCount: number;
  /** Live upload progress (only populated while currentStep === "uploading"). */
  uploadBytesTotal: number;
  uploadBytesDone: number;
  uploadStartedAtMs: number;
  /** Whether the `openclaw` CLI is on PATH. A prerequisite ONLY on the
   *  OpenClaw edition, where the archive is made by `openclaw backup create`.
   *  Kept as the raw fact; `archiverReady` is the question the UI asks. */
  openclawInstalled: boolean;
  daemonInstalled: boolean;
  /** Which agent's state a backup on this box captures. Mirrors
   *  `clawkeep.agent.device_agent()` in the daemon, which is the authority —
   *  the daemon is what actually picks the backend. */
  agent: HarnessId;
  /** Is there anything left to install before a backup can run?
   *
   *  On OpenClaw this is `openclawInstalled`: no CLI, no archive. On Hermes the
   *  archiver lives inside the daemon (`clawkeep/hermes.py`), so once the
   *  daemon is there the box can back up — there is no second binary and no
   *  `npm install -g openclaw` remedy to print, which would contradict the SKU.
   */
  archiverReady: boolean;
  /** True when a snapshot from this box carries provider keys or platform
   *  tokens, so the UI can say a backup is a credential. Both editions do. */
  backupContainsCredentials: boolean;
  /** Retained for older clients that gate the whole app on it. ClawKeep now
   *  supports BOTH editions, so it is always true; the honest per-edition
   *  answer is `archiverReady`. */
  supportedOnEdition: boolean;
  /** True while a restore is mid-flight (download → verify → swap). */
  restoring: boolean;
  /** Schedule for unattended backups. `enabled=false` disarms the in-process scheduler. */
  schedule: ClawKeepSchedule;
  /** Wall-clock ms of the next scheduled run, or 0 when disabled. */
  nextRunAtMs: number;
  /** True when the device-local passphrase file is present (and non-empty).
   * `paired && !encryptionConfigured` is the gate the UI watches to surface
   * the "Set encryption passphrase" CTA before the first backup. */
  encryptionConfigured: boolean;
}

export class ClawKeepError extends Error {
  constructor(
    message: string,
    readonly status: number = 500,
    /** Machine-readable reason, echoed by the routes as `code`. Present only
     * where a caller has to branch on the failure; a client must never have to
     * match on the English sentence to do it. */
    readonly code?: string,
  ) {
    super(message);
    this.name = "ClawKeepError";
  }
}

/** The one sentence, and the one code, for "this box has no ClawKeep pairing".
 * Every path that needs the daemon answers exactly this, so the app, the MCP
 * tools and the scheduler all see one failure instead of six. */
class ClawKeepNotPairedError extends ClawKeepError {
  constructor() {
    super("ClawKeep is not paired with an account", 409, "not_paired");
    this.name = "ClawKeepNotPairedError";
  }
}

/** The body a ClawKeep route answers a failure with: the sentence, plus the
 * `code` when the error carries one. One helper so every route in the folder
 * reports a failure the same way and a caller never has to read the English. */
export function clawKeepErrorBody(err: unknown, fallback: string): {
  error: string;
  code?: string;
} {
  const error = err instanceof Error && err.message ? err.message : fallback;
  const code = err instanceof ClawKeepError ? err.code : undefined;
  return code ? { error, code } : { error };
}

// ────────────────────────────────────────────────────────────────────
// File helpers
// ────────────────────────────────────────────────────────────────────

async function ensureDataDir(): Promise<void> {
  await fs.mkdir(CLAWKEEP_DATA_DIR, { recursive: true, mode: 0o700 });
}

// Stale-flag window: if the restoring marker is older than the restore
// timeout it almost certainly means the Next.js process crashed mid-run
// and never cleaned up. Treat as not-restoring so the shield stops glowing.
const RESTORING_FLAG_MAX_AGE_MS = 30 * 60 * 1000;

function sanitiseSchedule(input: unknown): ClawKeepSchedule {
  // Coerce-and-default: tolerate a missing/partial schedule file rather than
  // crash the daemon. Only the four well-known fields are honoured; anything
  // else is silently dropped so future schema changes can't poison the file.
  const r = (input ?? {}) as Record<string, unknown>;
  const frequency: ScheduleFrequency =
    r.frequency === "weekly" ? "weekly" : "daily";
  const time = typeof r.timeOfDay === "string" && /^\d{2}:\d{2}$/.test(r.timeOfDay)
    ? r.timeOfDay
    : DEFAULT_SCHEDULE.timeOfDay;
  const weekdayRaw = Number(r.weekday);
  const weekday = Number.isInteger(weekdayRaw) && weekdayRaw >= 0 && weekdayRaw <= 6
    ? weekdayRaw
    : DEFAULT_SCHEDULE.weekday;
  // retentionKeepLast: a non-negative integer; 0 disables. Anything bogus
  // falls back to the default so a malformed file can't silently turn off
  // retention (which would let snapshots accumulate forever).
  const keepRaw = Number(r.retentionKeepLast);
  const retentionKeepLast = Number.isInteger(keepRaw) && keepRaw >= 0
    ? keepRaw
    : DEFAULT_SCHEDULE.retentionKeepLast;
  return {
    enabled: r.enabled === true,
    frequency,
    timeOfDay: time,
    weekday,
    retentionKeepLast,
  };
}

export async function readSchedule(): Promise<ClawKeepSchedule> {
  try {
    const raw = await fs.readFile(SCHEDULE_PATH, "utf8");
    return sanitiseSchedule(JSON.parse(raw));
  } catch {
    return { ...DEFAULT_SCHEDULE };
  }
}

export async function writeSchedule(next: ClawKeepSchedule): Promise<ClawKeepSchedule> {
  await ensureDataDir();
  const sanitised = sanitiseSchedule(next);
  const tmp = `${SCHEDULE_PATH}.tmp`;
  await fs.writeFile(tmp, JSON.stringify(sanitised, null, 2), { mode: 0o600 });
  await fs.rename(tmp, SCHEDULE_PATH);
  return sanitised;
}

/** Compute the next wall-clock ms a backup should fire, given a schedule
 * and a "now" reference. Pure function — exported for unit tests. */
export function computeNextRunMs(schedule: ClawKeepSchedule, now: Date): number {
  if (!schedule.enabled) return 0;
  const [h, m] = schedule.timeOfDay.split(":").map((s) => Number(s));
  if (!Number.isInteger(h) || !Number.isInteger(m) || h < 0 || h > 23 || m < 0 || m > 59) {
    return 0;
  }
  const candidate = new Date(now);
  candidate.setHours(h, m, 0, 0);
  if (schedule.frequency === "daily") {
    if (candidate.getTime() <= now.getTime()) {
      candidate.setDate(candidate.getDate() + 1);
    }
    return candidate.getTime();
  }
  // Weekly — advance until the candidate is in the future AND lands on the target weekday.
  if (!Number.isInteger(schedule.weekday)) return 0;
  const target = ((schedule.weekday % 7) + 7) % 7;
  // At most 8 day-advances are needed (today + 7 days), so a guard of 9
  // hops trips only on a clock/DST anomaly we'd rather skip than spin on.
  for (let hops = 0; hops < 9; hops++) {
    if (candidate.getDay() === target && candidate.getTime() > now.getTime()) {
      return candidate.getTime();
    }
    candidate.setDate(candidate.getDate() + 1);
  }
  return 0;
}

async function setRestoring(active: boolean): Promise<void> {
  await ensureDataDir();
  if (active) {
    await fs.writeFile(RESTORING_FLAG_PATH, "", { mode: 0o600 });
  } else {
    await fs.rm(RESTORING_FLAG_PATH, { force: true });
  }
}

async function isRestoring(): Promise<boolean> {
  let stat;
  try {
    stat = await fs.stat(RESTORING_FLAG_PATH);
  } catch {
    return false;
  }
  // Use mtime as the age signal — saves an open+read on the hot path
  // (5 s polls) where the file usually doesn't exist anyway.
  if (Date.now() - stat.mtimeMs > RESTORING_FLAG_MAX_AGE_MS) {
    await fs.rm(RESTORING_FLAG_PATH, { force: true });
    return false;
  }
  return true;
}

async function writeSecret(p: string, contents: string): Promise<void> {
  await ensureDataDir();
  // Atomic-rename a 0600 tmp file so the secret is never world-readable
  // even on a crash mid-write.
  const tmp = `${p}.tmp`;
  const handle = await fs.open(tmp, "w", 0o600);
  try {
    await handle.writeFile(contents, "utf8");
  } finally {
    await handle.close();
  }
  await fs.chmod(tmp, 0o600);
  await fs.rename(tmp, p);
}

// ────────────────────────────────────────────────────────────────────
// Token / config / state
// ────────────────────────────────────────────────────────────────────

export async function readToken(): Promise<string | null> {
  try {
    const raw = (await fs.readFile(TOKEN_PATH, "utf8")).trim();
    if (!raw.startsWith("claw_")) return null;
    return raw;
  } catch (e) {
    if ((e as NodeJS.ErrnoException).code === "ENOENT") return null;
    throw e;
  }
}

export async function writeToken(token: string): Promise<void> {
  if (!token.startsWith("claw_")) {
    throw new ClawKeepError("refusing to write non-claw_* token", 400);
  }
  await writeSecret(TOKEN_PATH, token);
}

export async function deleteToken(): Promise<void> {
  await fs.unlink(TOKEN_PATH).catch((e) => {
    if ((e as NodeJS.ErrnoException).code !== "ENOENT") throw e;
  });
}

/**
 * Forget this device's ClawKeep pairing locally: delete the token and clear
 * the in-flight "running" state. Does NOT revoke server-side, and deliberately
 * keeps config.toml / passphrase / schedule so a re-pair against a new account
 * reuses the same encryption + schedule. Shared by the unpair route and the
 * ClawBox-AI-account-change reset so the two stay in lockstep.
 *
 * `clearStats` controls what happens to the historical "last successful"
 * numbers (last backup time / cloud size / snapshot count):
 *  - false (default, manual "unpair this device"): keep them, since the user
 *    may re-pair the same account and shouldn't lose their protection history.
 *  - true (ClawBox AI account change): wipe them — they belong to the previous
 *    account, so leaving them would make the new account's "you're protected"
 *    screen show the old account's snapshot count and size.
 */
export async function unpairLocal(opts: { clearStats?: boolean } = {}): Promise<void> {
  await deleteToken();
  if (opts.clearStats) {
    await fs.rm(STATE_PATH, { force: true }).catch((err) => {
      console.warn("[clawkeep] could not clear state.json during account-change unpair (continuing):", err);
    });
  } else {
    await resetRunningState().catch((err) => {
      console.warn("[clawkeep] could not reset state.json during unpair (continuing):", err);
    });
  }
}

/**
 * Clear the in-flight tracking fields in state.json so the dashboard
 * stops showing a "running" spinner inherited from a daemon that was
 * killed mid-backup (systemd restart, OOM, manual `kill`, etc.).
 *
 * Preserves the historical "last successful" stats — `last_backup_at_ms`,
 * `last_cloud_bytes`, `last_snapshot_count` — so the user doesn't lose
 * the "you're protected" history just because they cleared a stuck
 * spinner. Idempotent: if state.json doesn't exist or the fields are
 * already clean, this is a no-op.
 */
export async function resetRunningState(): Promise<void> {
  let raw: string;
  try {
    raw = await fs.readFile(STATE_PATH, "utf8");
  } catch (e) {
    if ((e as NodeJS.ErrnoException).code === "ENOENT") return;
    throw e;
  }
  let parsed: StateFile;
  try {
    parsed = JSON.parse(raw) as StateFile;
  } catch {
    parsed = {};
  }
  const cleaned: StateFile = {
    last_backup_at_ms: parsed.last_backup_at_ms ?? 0,
    last_cloud_bytes: parsed.last_cloud_bytes ?? 0,
    last_snapshot_count: parsed.last_snapshot_count ?? 0,
    last_heartbeat_at_ms: parsed.last_heartbeat_at_ms ?? 0,
    last_heartbeat_status: "",
    last_step: "",
    last_step_at_ms: 0,
    upload_bytes_total: 0,
    upload_bytes_done: 0,
    upload_started_at_ms: 0,
  };
  await writeStateFile(cleaned);
}

/**
 * Atomically write state.json (temp file + rename, mode 0600) so a concurrent
 * reader never sees a half-written file. Shared by resetRunningState() and
 * syncStateFromCloud().
 */
let stateWriteSeq = 0;

async function writeStateFile(state: StateFile): Promise<void> {
  await ensureDataDir();
  // Per-call temp name (pid + monotonic counter) so concurrent writers — e.g.
  // a pair-time cloud sync racing a stuck-spinner reset — can't clobber each
  // other's temp file before the atomic rename.
  const tmp = `${STATE_PATH}.tmp.${process.pid}.${++stateWriteSeq}`;
  await fs.writeFile(tmp, JSON.stringify(state, null, 2), { mode: 0o600 });
  await fs.rename(tmp, STATE_PATH);
}

export async function readConfigToml(): Promise<string> {
  try {
    return await fs.readFile(CLAWKEEP_CONFIG_PATH, "utf8");
  } catch (e) {
    if ((e as NodeJS.ErrnoException).code !== "ENOENT") throw e;
  }
  // Race-safe seed: O_CREAT|O_EXCL means concurrent first-run callers
  // can't double-write; whichever loses gets EEXIST and reads the winner's
  // content on the next pass.
  await ensureDataDir();
  try {
    const handle = await fs.open(CLAWKEEP_CONFIG_PATH, "wx", 0o644);
    try {
      await handle.writeFile(DEFAULT_CONFIG_TOML, "utf8");
    } finally {
      await handle.close();
    }
  } catch (e) {
    if ((e as NodeJS.ErrnoException).code !== "EEXIST") throw e;
  }
  return fs.readFile(CLAWKEEP_CONFIG_PATH, "utf8");
}

interface StateFile {
  last_heartbeat_at_ms?: number;
  last_heartbeat_status?: string;
  last_step?: string;
  last_step_at_ms?: number;
  last_backup_at_ms?: number;
  last_cloud_bytes?: number;
  last_snapshot_count?: number;
  upload_bytes_total?: number;
  upload_bytes_done?: number;
  upload_started_at_ms?: number;
}

/** Pull just the `server` value out of a config.toml. The Python daemon does
 * the full strict parse; we only need this scalar for the dashboard tagline. */
function readServer(toml: string): string {
  for (const raw of toml.split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    if (line.startsWith("[")) break; // server lives in the top-level section
    const eq = line.indexOf("=");
    if (eq < 0) continue;
    if (line.slice(0, eq).trim() !== "server") continue;
    const m = line.slice(eq + 1).trim().match(/^"([^"]*)"/);
    if (m) return m[1];
  }
  return DEFAULT_PORTAL_SERVER;
}

async function readStateFile(): Promise<StateFile> {
  try {
    return JSON.parse(await fs.readFile(STATE_PATH, "utf8")) as StateFile;
  } catch {
    return {};
  }
}

// ────────────────────────────────────────────────────────────────────
// Binary discovery (memoised)
// ────────────────────────────────────────────────────────────────────

function which(bin: string): Promise<boolean> {
  return new Promise((resolve) => {
    const p = spawn("which", [bin], { stdio: "ignore" });
    p.on("error", () => resolve(false));
    p.on("close", (code) => resolve(code === 0));
  });
}

// systemd's secure_path doesn't include ~/.local/bin or ~/.npm-global/bin,
// so a pip --user install of clawkeepd and an `npm install -g openclaw`
// both miss PATH for the Next.js process. We probe the canonical
// install locations as fallbacks. Cache *successful* lookups for the
// process lifetime — a positive answer doesn't change without a
// restart.
let daemonBinCache: string | null = null;

async function getOpenclawInstalled(): Promise<boolean> {
  // findOpenclawBin() returns the literal "openclaw" when none of its
  // absolute candidates exist; in that case fall back to a $PATH probe so
  // a system install (apt/yum) still counts as "installed".
  const resolved = findOpenclawBin();
  if (resolved !== "openclaw") return true;
  return await which("openclaw");
}

async function getDaemonBin(): Promise<string | null> {
  if (daemonBinCache) return daemonBinCache;
  const override = process.env.CLAWKEEP_BIN?.trim();
  if (override) {
    // Checked, not trusted. An override left pointing at a path that no longer
    // exists used to report the daemon as installed, which now also reports
    // `archiverReady: true` — a box that cannot back up telling the owner it
    // can. A bad override falls through to the normal probe rather than
    // failing outright, so a stale env var degrades to "look for it properly".
    try {
      // isFile() as well as X_OK: a DIRECTORY passes the executable check
      // (that is what the x bit means on a directory), and caching one would
      // report the daemon as installed and the box as ready to back up.
      const stat = await fs.stat(override);
      if (!stat.isFile()) throw new Error("not a regular file");
      await fs.access(override, fsConstants.X_OK);
      daemonBinCache = override;
      return override;
    } catch {
      // fall through to the PATH / user-local probes below
    }
  }
  if (await which(DEFAULT_BIN_NAME)) {
    daemonBinCache = DEFAULT_BIN_NAME;
    return DEFAULT_BIN_NAME;
  }
  const fallback = path.join(os.homedir(), ".local", "bin", DEFAULT_BIN_NAME);
  try {
    await fs.access(fallback);
    daemonBinCache = fallback;
    return fallback;
  } catch {
    return null;
  }
}

/**
 * The daemon binary for a call that needs the pairing token, refused before it
 * can spawn anything when the device has none.
 *
 * The pairing signal is the daemon's own: `clawkeep/clawkeep/token.py`
 * `read_token()` raises `TokenError("No token at <path>; run 'clawkeep pair'
 * first")`, which `clawkeepd` returns as exit 65 and every token-taking
 * `clawkeep` subcommand as `{"ok":false,"error":"No token at <path>…"}`.
 * Reading the same file first is what lets a route answer the owner one
 * sentence instead of quoting a daemon log line that names a path on the box.
 *
 * Everything that reaches the portal comes through here — `clawkeepd` itself
 * and `snapshots`, `restore`, `label`, `lock`, `delete`, `prune`. The
 * `*-passphrase` subcommands deliberately do NOT: they are device-local, and a
 * box has to be able to set its encryption passphrase before it is paired.
 */
async function pairedDaemonBin(): Promise<string> {
  if (!(await readToken())) throw new ClawKeepNotPairedError();
  return (await getDaemonBin()) ?? DEFAULT_BIN_NAME;
}

/** Build the env for spawning the Python daemon/CLI. Augments PATH with the
 *  resolved openclaw bin's directory + the user-local bin dirs so the daemon's
 *  own `subprocess.run(["openclaw", ...])` resolves under systemd's stripped
 *  PATH. Centralised so spawn sites stay in lockstep. */
function buildSpawnEnv(): NodeJS.ProcessEnv {
  const extraDirs = new Set<string>();
  const resolved = findOpenclawBin();
  if (resolved !== "openclaw") extraDirs.add(path.dirname(resolved));
  extraDirs.add(path.join(os.homedir(), ".local", "bin"));
  extraDirs.add(path.join(os.homedir(), ".npm-global", "bin"));

  const parentPath = process.env.PATH ?? "";
  const prefix = Array.from(extraDirs).join(path.delimiter);
  const augmentedPath = parentPath ? `${prefix}${path.delimiter}${parentPath}` : prefix;
  return { ...process.env, CLAWKEEP_DATA_DIR, PATH: augmentedPath };
}

// ────────────────────────────────────────────────────────────────────
// Status
// ────────────────────────────────────────────────────────────────────

export async function isEncryptionConfigured(): Promise<boolean> {
  // Mirror the Python `passphrase.is_set()` check: file exists AND is
  // non-empty. A 0-byte file is treated as "not configured" so a botched
  // first-write doesn't get interpreted as an empty passphrase.
  try {
    const st = await fs.stat(PASSPHRASE_PATH);
    return st.isFile() && st.size > 0;
  } catch {
    return false;
  }
}

/**
 * Stage `secret` in a 0600 tmpfile, run `fn` with its path, then wipe
 * (zero-overwrite + rm) the file regardless of outcome. Used to hand
 * passphrases to the Python CLI without ever putting them on argv.
 *
 * The wipe is best-effort: tmpfs is volatile and the swap-out window is
 * short, but the overwrite is cheap (≤ a few hundred bytes) and a real
 * defence on disk-backed /tmp.
 */
async function withSecretTmpfile<T>(
  secret: string,
  fn: (tmpFile: string) => Promise<T>,
): Promise<T> {
  const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), "clawkeep-pw-"));
  const tmpFile = path.join(tmpDir, "pw");
  try {
    const fd = await fs.open(tmpFile, "w", 0o600);
    try {
      await fd.writeFile(secret, "utf8");
    } finally {
      await fd.close();
    }
    return await fn(tmpFile);
  } finally {
    try {
      const sz = (await fs.stat(tmpFile)).size;
      if (sz > 0) {
        const fd = await fs.open(tmpFile, "r+");
        try {
          // Cryptographically random bytes rather than zeros so a
          // forensic disk pass can't tell apart "this file held a
          // secret" from any other random tmpfile. Mirrors the Python
          // side's os.urandom() approach in clawkeep/crypto.py.
          await fd.write(randomBytes(sz), 0, sz, 0);
        } finally {
          await fd.close();
        }
      }
    } catch { /* tmpfile may already be gone */ }
    await fs.rm(tmpDir, { recursive: true, force: true });
  }
}

export async function setPassphrase(passphrase: string): Promise<void> {
  // Reject empty / whitespace-only here too — the Python side also
  // rejects, but bouncing it before we shell out gives the API a clean
  // 400 instead of the daemon's 64-coded error envelope.
  if (!passphrase || !passphrase.trim()) {
    throw new ClawKeepError("passphrase must be non-empty", 400);
  }
  await ensureDataDir();
  await withSecretTmpfile(passphrase, async (tmpFile) => {
    const bin = (await getDaemonBin()) ?? DEFAULT_BIN_NAME;
    const resp = await spawnCliJson<{ ok: boolean; error?: string }>(
      bin,
      "set-passphrase",
      ["--from-file", tmpFile],
      { timeoutMs: 10_000 },
    );
    if (!resp.ok) {
      throw new ClawKeepError(resp.error ?? "set-passphrase failed", 502);
    }
  });
}

export async function clearPassphrase(): Promise<{ removed: boolean }> {
  const bin = (await getDaemonBin()) ?? DEFAULT_BIN_NAME;
  const resp = await spawnCliJson<{ ok: boolean; removed?: boolean; error?: string }>(
    bin,
    "clear-passphrase",
    [],
    { timeoutMs: 10_000 },
  );
  if (!resp.ok) {
    throw new ClawKeepError(resp.error ?? "clear-passphrase failed", 502);
  }
  return { removed: resp.removed ?? false };
}

export async function getStatus(): Promise<ClawKeepStatus> {
  await ensureDataDir();
  const [token, configToml, stateRaw, openclawInstalled, daemonBin, restoring, schedule, encryptionConfigured] = await Promise.all([
    readToken(),
    readConfigToml(),
    readStateFile(),
    getOpenclawInstalled(),
    getDaemonBin(),
    isRestoring(),
    readSchedule(),
    isEncryptionConfigured(),
  ]);

  const server = readServer(configToml);
  // A single-harness edition names its own agent. "dual" installs both and
  // defaults to OpenClaw (`DEFAULT_HARNESS` in harness.ts), which is also what
  // the daemon's `device_agent()` picks when both state directories exist — the
  // two must agree, because the daemon is what actually builds the archive.
  const agent: HarnessId = getEdition() === "hermes" ? "hermes" : "openclaw";
  const source = backupSourceFor(agent);
  return {
    paired: !!token,
    // openclaw decides what's in the archive — we no longer ask the user
    // to declare paths, so any paired device with a valid config is
    // "configured" enough to run.
    configured: !!token && server.length > 0,
    server,
    lastBackupAtMs: stateRaw.last_backup_at_ms ?? 0,
    lastHeartbeatAtMs: stateRaw.last_heartbeat_at_ms ?? 0,
    lastHeartbeatStatus: (stateRaw.last_heartbeat_status ?? "") as HeartbeatStatus,
    cloudBytes: stateRaw.last_cloud_bytes ?? 0,
    snapshotCount: stateRaw.last_snapshot_count ?? 0,
    currentStep: stateRaw.last_step ?? "",
    currentStepAtMs: stateRaw.last_step_at_ms ?? 0,
    uploadBytesTotal: stateRaw.upload_bytes_total ?? 0,
    uploadBytesDone: stateRaw.upload_bytes_done ?? 0,
    uploadStartedAtMs: stateRaw.upload_started_at_ms ?? 0,
    openclawInstalled,
    daemonInstalled: daemonBin !== null,
    agent,
    // "Is there anything left to install before a backup can run?"
    //
    // The daemon is required on BOTH editions — it is the thing that runs, and
    // on Hermes it is also where the archiver itself lives. Reporting `true`
    // for Hermes on a box with no `clawkeepd` said the backup path was usable
    // on a device that cannot create a backup at all. OpenClaw needs the
    // separate `openclaw` CLI on top of that.
    archiverReady:
      daemonBin !== null && (source.requiresExternalCli ? openclawInstalled : true),
    backupContainsCredentials: source.containsCredentials,
    // ClawKeep now archives EITHER agent (see `clawkeep/agent.py`), so no
    // edition is unsupported. Kept true rather than deleted so a client that
    // still gates on it keeps working.
    supportedOnEdition: true,
    restoring,
    schedule,
    nextRunAtMs: computeNextRunMs(schedule, new Date()),
    encryptionConfigured,
  };
}

// ────────────────────────────────────────────────────────────────────
// Backup runs — spawn `clawkeepd --once` (or --idle)
// ────────────────────────────────────────────────────────────────────

export interface BackupResult {
  exitCode: number;
  stdout: string;
  stderr: string;
}

// Cap stdout/stderr capture so a chatty `openclaw backup create` over a
// large workspace can't OOM the Next.js process. We only show a 2 KB tail
// in the UI anyway, so keeping a generous tail buffer (64 KB) leaves plenty
// of room for the final summary line + any stderr trace while staying
// bounded.
const MAX_OUTPUT_BYTES = 64 * 1024;

function appendCapped(prev: string, chunk: string): string {
  const next = prev + chunk;
  if (next.length <= MAX_OUTPUT_BYTES) return next;
  return next.slice(next.length - MAX_OUTPUT_BYTES);
}

export interface CloudSnapshot {
  name: string;
  size_bytes: number;
  last_modified_ms: number;
  /** Human label from the sidecar manifest; null/undefined = unnamed. */
  label?: string | null;
  /** Protected flag — a locked snapshot can't be deleted (manual or auto). */
  locked?: boolean;
}

interface SnapshotsResponse {
  ok: boolean;
  error?: string;
  /** Coarse failure classification from the daemon so we can map to a
   * sensible HTTP status instead of collapsing everything into 502. */
  kind?: string;
  snapshots?: CloudSnapshot[];
  quotaBytes?: number;
  cloudBytes?: number;
}

/**
 * Map a failed `snapshots` daemon response to an HTTP status + a friendly
 * message. We deliberately never surface `resp.error` verbatim — it can be a
 * raw Python traceback or leak internal paths — so the caller gets a clean,
 * classified error the UI can act on.
 */
function mapSnapshotsError(resp: SnapshotsResponse): ClawKeepError {
  switch (resp.kind) {
    case "unpaired":
    case "no_token":
    case "not_paired":
      // Same answer as the pre-flight check, IF the daemon ever says so: today
      // `clawkeep snapshots` classifies nothing — `cli.py::_emit_err` prints
      // `{"ok":false,"error":…}` with no `kind` for `TokenError` too, so these
      // cases are unreached and the token vanishing mid-session still falls to
      // `default:` (502). Kept as the mapping to use when the daemon starts
      // classifying its errors — which needs a `no_token` kind that
      // `api.ApiError` does not have either (its union is auth | quota_full |
      // tier | server | network | other), so making this branch live is a
      // daemon-side change, not just a wiring one.
      return new ClawKeepNotPairedError();
    case "auth":
    case "unauthorized":
    case "revoked":
    case "forbidden":
      return new ClawKeepError(
        "ClawKeep authorisation was rejected — re-pair the device",
        401,
      );
    case "network":
    case "offline":
    case "timeout":
      return new ClawKeepError("Could not reach the ClawKeep portal", 504);
    case "portal":
    case "server":
      return new ClawKeepError("The ClawKeep portal returned an error", 502);
    default:
      // Covers missing-dependency (e.g. boto3) and any unclassified daemon
      // failure without leaking the raw internal string.
      return new ClawKeepError("Could not list cloud backups", 502);
  }
}

interface RestoreOk {
  ok: true;
  archive: string;
  archiveBytes: number;
  /** Members the daemon deliberately did not recreate — unsafe absolute
   *  symlinks. Normally empty; when it is not, the restore is INCOMPLETE and
   *  the UI has to say so rather than showing a clean success. Optional
   *  because a daemon predating the field simply omits it. */
  skippedMembers?: string[];
  assets: { kind: string; targetPath: string; backupPath: string; bytesRestored: number }[];
}

interface RestoreErr {
  ok: false;
  error: string;
  /** Distinct error kinds the daemon emits so the UI can react with the
   * right modal — otherwise `error: "..."` is opaque. */
  kind?: "wrong_password" | "passphrase_missing";
}

type RestoreCliResponse = RestoreOk | RestoreErr;

/** Thrown by runRestore when the daemon needs a passphrase the device
 * doesn't currently have stored. The UI catches this and prompts. */
export class RestoreNeedsPassphraseError extends ClawKeepError {
  constructor(message: string, readonly kind: "wrong_password" | "passphrase_missing") {
    super(message, 401);
    this.name = "RestoreNeedsPassphraseError";
  }
}

const RESTORE_TIMEOUT_MS = 30 * 60 * 1000; // hard cap matches openclaw verify + multipart download
// Generous cap for a full backup (openclaw backup create + multipart upload).
// A hung clawkeepd must not hold a Next.js worker open forever.
const BACKUP_TIMEOUT_MS = 60 * 60 * 1000;

function spawnCliJson<T>(
  bin: string,
  subcommand: string,
  extraArgs: string[],
  opts: { timeoutMs: number },
): Promise<T> {
  const { timeoutMs } = opts;
  return new Promise((resolve, reject) => {
    const env = buildSpawnEnv();

    // The real `clawkeep` script lives next to clawkeepd. If we resolved
    // clawkeepd to ~/.local/bin/clawkeepd, derive the sibling `clawkeep`
    // binary path; the system PATH version may not exist.
    const clawkeepBin = bin.endsWith("clawkeepd")
      ? bin.replace(/clawkeepd$/, "clawkeep")
      : "clawkeep";

    // `--config` is a per-subcommand flag in cli.py — order is
    // `clawkeep <subcommand> [<positional>] --config <path>`.
    const args = [subcommand, ...extraArgs, "--config", CLAWKEEP_CONFIG_PATH];
    const child = spawn(clawkeepBin, args, { env, stdio: ["ignore", "pipe", "pipe"] });

    let stdout = "";
    let stderr = "";
    // Decode through a StringDecoder so a multibyte UTF-8 sequence split across
    // two 'data' events (e.g. a Cyrillic snapshot label straddling a chunk
    // boundary) isn't corrupted into U+FFFD — the decoder buffers the partial
    // trailing bytes until the next chunk (flushed via .end() on close).
    const outDecoder = new StringDecoder("utf8");
    const errDecoder = new StringDecoder("utf8");
    const killTimer = setTimeout(() => {
      try { child.kill("SIGKILL"); } catch { /* already gone */ }
    }, timeoutMs);

    child.stdout.on("data", (b: Buffer) => {
      stdout = appendCapped(stdout, outDecoder.write(b));
    });
    child.stderr.on("data", (b: Buffer) => {
      stderr = appendCapped(stderr, errDecoder.write(b));
    });
    child.on("error", (err) => {
      clearTimeout(killTimer);
      // An unresolved binary (clawkeep/clawkeepd not on PATH or the derived
      // sibling missing) surfaces as ENOENT. Turn it into a friendly 503
      // instead of a raw "spawn ... ENOENT" 500.
      if ((err as NodeJS.ErrnoException).code === "ENOENT") {
        reject(new ClawKeepError("ClawKeep daemon not installed", 503));
        return;
      }
      reject(new Error(`spawn ${clawkeepBin} failed: ${err.message}`));
    });
    child.on("close", (code) => {
      clearTimeout(killTimer);
      // Flush any bytes the decoder is still holding (a trailing partial
      // multibyte sequence) before parsing.
      stdout = appendCapped(stdout, outDecoder.end());
      stderr = appendCapped(stderr, errDecoder.end());
      // Both `clawkeep snapshots` and `clawkeep restore` print a single JSON
      // object on stdout — even on errors. Parse first; fall back to stderr
      // text if parsing fails so the caller still gets a usable message.
      try {
        const parsed = JSON.parse(stdout.trim().split("\n").pop() || "{}") as T;
        resolve(parsed);
      } catch {
        reject(
          new Error(
            `clawkeep ${subcommand} exited ${code ?? "?"}; ` +
              `non-JSON output. stderr=${stderr.slice(-500)}`,
          ),
        );
      }
    });
  });
}

async function fetchCloudSnapshots(): Promise<SnapshotsResponse> {
  // Fail fast + friendly on the unpaired case rather than shelling out and
  // surfacing the daemon's raw "no token" error as a 502.
  const bin = await pairedDaemonBin();
  const resp = await spawnCliJson<SnapshotsResponse>(bin, "snapshots", [], { timeoutMs: 60_000 });
  if (!resp.ok) {
    throw mapSnapshotsError(resp);
  }
  return resp;
}

export async function listCloudSnapshots(): Promise<CloudSnapshot[]> {
  return (await fetchCloudSnapshots()).snapshots ?? [];
}

/**
 * Seed state.json from the account's existing cloud snapshots.
 *
 * The dashboard's "last backup / cloud size / snapshot count" all come from
 * state.json, which is only written by a *local* backup run. So right after
 * (re)pairing an account that already has backups in the cloud, the device
 * has no local record of them and would show "0 B / 0 / never" until the next
 * backup. Pulling the real snapshot list on pair fixes that — the dashboard
 * reflects what's actually in the account's cloud prefix immediately.
 *
 * Best-effort: a cloud-list failure (offline, portal hiccup, daemon missing)
 * leaves state.json untouched rather than blocking the pair. Combined with the
 * account-change `unpairLocal({ clearStats })` wipe, an offline re-pair then
 * shows a clean slate instead of the previous account's numbers.
 */
export async function syncStateFromCloud(): Promise<void> {
  let resp: SnapshotsResponse;
  try {
    resp = await fetchCloudSnapshots();
  } catch (err) {
    console.warn("[clawkeep] cloud snapshot sync after pair failed (continuing):", err);
    return;
  }
  const snapshots = resp.snapshots ?? [];
  const lastBackupAtMs = snapshots.reduce((max, s) => Math.max(max, s.last_modified_ms ?? 0), 0);
  // Prefer the daemon's authoritative prefix total; fall back to summing the
  // per-snapshot sizes only if an older daemon doesn't report cloudBytes.
  const cloudBytes = resp.cloudBytes ?? snapshots.reduce((sum, s) => sum + (s.size_bytes ?? 0), 0);
  await writeStateFile({
    last_backup_at_ms: lastBackupAtMs,
    last_cloud_bytes: cloudBytes,
    last_snapshot_count: snapshots.length,
    last_heartbeat_at_ms: lastBackupAtMs,
    last_heartbeat_status: "",
    last_step: "",
    last_step_at_ms: 0,
    upload_bytes_total: 0,
    upload_bytes_done: 0,
    upload_started_at_ms: 0,
  });
}

// ────────────────────────────────────────────────────────────────────
// Snapshot management — label / lock / unlock / delete / prune
// ────────────────────────────────────────────────────────────────────

// Snapshot object names are portal-issued `<ts>-openclaw-backup.tar.gz(.enc)`.
// Validate the shape on this side too (same regex the restore path uses) so a
// hostile/garbled name is bounced with a clean 400 before we shell out — it
// could never escape the portal-issued prefix anyway, but the early reject is
// clearer for the user.
// NOTE: names include a `+` from the ISO timestamp's tz offset (e.g.
// `...57.761+03-00-openclaw-backup.tar.gz.enc`), so `+` must be allowed or
// every real snapshot is bounced with "invalid snapshot name" on restore.
const SNAPSHOT_NAME_RE = /^[A-Za-z0-9._+-]+\.tar\.gz(\.enc)?$/;

function assertSnapshotName(name: string): void {
  if (!SNAPSHOT_NAME_RE.test(name)) {
    throw new ClawKeepError("invalid snapshot name", 400);
  }
}

/** Thrown when a delete is refused because the snapshot is locked. The route
 * maps this to a 409 with `kind:"locked"` so the UI can say "Unlock first". */
export class SnapshotLockedError extends ClawKeepError {
  constructor(message: string, readonly kind: "locked" = "locked") {
    super(message, 409);
    this.name = "SnapshotLockedError";
  }
}

interface MutationResponse {
  ok: boolean;
  error?: string;
  kind?: string;
}

/** Set (or clear, when `text` is empty) a snapshot's human label. */
export async function setSnapshotLabel(name: string, text: string): Promise<void> {
  assertSnapshotName(name);
  const bin = await pairedDaemonBin();
  const resp = await spawnCliJson<MutationResponse>(
    bin,
    "label",
    [name, "--text", text],
    { timeoutMs: 30_000 },
  );
  if (!resp.ok) {
    throw new ClawKeepError(resp.error ?? "label failed", 502);
  }
}

/** Mark a snapshot as protected (locked) — exempt from delete + retention. */
export async function lockSnapshot(name: string): Promise<void> {
  assertSnapshotName(name);
  const bin = await pairedDaemonBin();
  const resp = await spawnCliJson<MutationResponse>(bin, "lock", [name], { timeoutMs: 30_000 });
  if (!resp.ok) {
    throw new ClawKeepError(resp.error ?? "lock failed", 502);
  }
}

/** Remove a snapshot's protected flag. */
export async function unlockSnapshot(name: string): Promise<void> {
  assertSnapshotName(name);
  const bin = await pairedDaemonBin();
  const resp = await spawnCliJson<MutationResponse>(bin, "unlock", [name], { timeoutMs: 30_000 });
  if (!resp.ok) {
    throw new ClawKeepError(resp.error ?? "unlock failed", 502);
  }
}

/** Delete a snapshot. Refused (SnapshotLockedError) if it's locked. */
export async function deleteSnapshot(name: string): Promise<void> {
  assertSnapshotName(name);
  const bin = await pairedDaemonBin();
  const resp = await spawnCliJson<MutationResponse>(bin, "delete", [name], { timeoutMs: 60_000 });
  if (!resp.ok) {
    if (resp.kind === "locked") {
      throw new SnapshotLockedError(resp.error ?? "snapshot is locked");
    }
    throw new ClawKeepError(resp.error ?? "delete failed", 502);
  }
}

/** Run retention on demand: keep the newest `keepLast` unlocked snapshots. */
export async function pruneSnapshots(keepLast: number): Promise<string[]> {
  const bin = await pairedDaemonBin();
  const resp = await spawnCliJson<MutationResponse & { deleted?: string[] }>(
    bin,
    "prune",
    ["--keep-last", String(Math.max(0, Math.floor(keepLast)))],
    { timeoutMs: 60_000 },
  );
  if (!resp.ok) {
    throw new ClawKeepError(resp.error ?? "prune failed", 502);
  }
  return resp.deleted ?? [];
}

export async function runRestore(
  name: string,
  opts: { passphrase?: string } = {},
): Promise<RestoreOk> {
  // Restore is destructive — sanity-check the name shape on this side too,
  // not just inside the Python CLI. A hostile input here couldn't escape the
  // prefix (we always concat with the portal-issued prefix on the Python
  // side) but bouncing it early gives the user a clearer error. Accept both
  // the new encrypted form (`.tar.gz.enc`) and the legacy unencrypted one
  // (`.tar.gz`); the daemon detects which is which on its end too.
  assertSnapshotName(name);
  const bin = await pairedDaemonBin();
  await setRestoring(true);
  try {
    const runWith = async (extraArgs: string[]) => {
      const resp = await spawnCliJson<RestoreCliResponse>(
        bin,
        "restore",
        [name, ...extraArgs],
        { timeoutMs: RESTORE_TIMEOUT_MS },
      );
      if (!resp.ok) {
        if (resp.kind === "wrong_password" || resp.kind === "passphrase_missing") {
          throw new RestoreNeedsPassphraseError(resp.error, resp.kind);
        }
        throw new ClawKeepError(resp.error, 502);
      }
      return resp;
    };
    // Stage a one-shot passphrase tmpfile when the caller supplied one, so
    // the password is fed via `--passphrase-file` rather than ever entering
    // argv (which would expose it in /proc/<pid>/cmdline).
    if (opts.passphrase) {
      return await withSecretTmpfile(opts.passphrase, (tmpFile) =>
        runWith(["--passphrase-file", tmpFile]),
      );
    }
    return await runWith([]);
  } finally {
    await setRestoring(false).catch(() => { /* best-effort cleanup */ });
  }
}

export async function runBackup(
  opts: { idle?: boolean; label?: string } = {},
): Promise<BackupResult> {
  const bin = await pairedDaemonBin();
  return new Promise((resolve) => {
    const env = buildSpawnEnv();
    const args = ["--config", CLAWKEEP_CONFIG_PATH];
    if (opts.idle) args.push("--idle");
    // Optional snapshot label from the UI's "Name this backup" field. Passed
    // as an argv pair (not a secret, unlike the passphrase) — the daemon
    // records it in the manifest after a successful upload.
    const label = opts.label?.trim();
    if (label) args.push("--label", label);
    const child = spawn(bin, args, { env, stdio: ["ignore", "pipe", "pipe"] });
    let stdout = "";
    let stderr = "";
    let settled = false;
    const settle = (result: BackupResult) => {
      if (settled) return;
      settled = true;
      clearTimeout(killTimer);
      resolve(result);
    };
    // Mirror spawnCliJson's kill-timer: SIGKILL a hung daemon and resolve
    // with a non-zero exit so the caller surfaces "backup timed out" rather
    // than leaking a worker forever.
    const killTimer = setTimeout(() => {
      try { child.kill("SIGKILL"); } catch { /* already gone */ }
      settle({ exitCode: 124, stdout, stderr: appendCapped(stderr, "\nbackup timed out") });
    }, BACKUP_TIMEOUT_MS);
    child.stdout.on("data", (b: Buffer) => {
      stdout = appendCapped(stdout, b.toString("utf8"));
    });
    child.stderr.on("data", (b: Buffer) => {
      stderr = appendCapped(stderr, b.toString("utf8"));
    });
    child.on("error", (e) => {
      // ENOENT etc. — synthesize a non-zero exit so callers can surface it.
      settle({ exitCode: 127, stdout, stderr: appendCapped(stderr, e.message) });
    });
    child.on("close", (code) => {
      settle({ exitCode: code ?? -1, stdout, stderr });
    });
  });
}
