"""ClawKeep's own boundary around `openclaw backup create`.

`openclaw backup create` is the archiver on the OpenClaw edition and it stays
the authority: its path-traversal, archive-root, symlink and SQLite-integrity
checks are not bypassed, loosened or re-implemented here. What this module owns
is everything ClawKeep does AROUND that call, for the failures field boxes hit
on OpenClaw 2026.9.4:

MANAGED LINKS
  The archiver refuses any symlink whose target lies outside the assets it
  declared ("Archive symbolic link target must be relative", then, for a
  relative one, "… is outside the declared backup assets") — and it refuses
  while WRITING, so the whole run fails. The core skips its own link trees
  only at the canonical state root (`<state>/plugin-skills`, `<state>/npm`,
  a registered plugin's `node_modules`); the same trees anywhere else in the
  backup fail it. On a real box: `plugin-skills/<skill> -> <global
  openclaw>/dist/extensions/…` inside the stray `~/.openclaw/.openclaw` tree
  and inside the Codex harness's own home, the `node_modules/openclaw` peer
  link the plugin installer writes, the Coding Agent's worktree
  `node_modules -> <project>/node_modules`, the legacy `plugin-runtime-deps/`
  cache an older core staged in the state dir. The explicit rule
  (:func:`managed_rule`) — a link the archiver would refuse is OMITTED when it
  is

      * package-manager output: named `node_modules`, below a `node_modules`
        directory, or below a pnpm store (`…/pnpm/store/…`);
      * OpenClaw's own plugin link: in a `plugin-skills` directory, or below
        `<state>/plugin-runtime-deps/`;
      * cache: below a `.cache` directory;
      * a Chromium `SingletonSocket` whose target is gone — the lock of a
        browser that is not running (a LIVE one is left alone: it is how a
        running browser is found).

  Each is regenerated by the tool that wrote it. It is omitted by DETACHING it
  for the length of the archive build — the link's own text is written to a
  journal first, the link is unlinked, and it is put back exactly as it was
  the moment the build ends, succeeded or not. A run killed mid-build (the
  bridge's four-hour cap sends SIGKILL) leaves the journal behind, and the
  next run puts the links back before it does anything else. The link is
  never followed: only its text is read.

  Every OTHER refused link is left exactly where it is and the archiver's
  refusal stands: ClawKeep never carries or follows a link out of the backup.
  The failure is reported as such, naming the link and where it points.

DUPLICATE LOGICAL PATHS
  Two planned assets that would be written to the same archive path — the
  same path, one inside the other, or two names only a case-insensitive
  filesystem tells apart — are refused BEFORE the archiver runs, naming both
  sources. A duplicate the archiver finds itself (while verifying) is mapped
  back to the source it was written from and reported the same way.

FILES THAT VANISH MID-WALK
  An ENOENT on a path inside the backup is a live-write race, not a broken box:
  it is marked transient so `runner` rebuilds the archive (bounded). The same
  sentence about a path OUTSIDE the backup is not a race and is not retried.

SQLITE INTEGRITY
  See :mod:`clawkeep.sqlite_recovery`: index-only damage is rebuilt, with a
  copy kept first, and the archive retried once per database; any other damage
  stops the backup with a sentence saying what it found and that ClawKeep left
  the database untouched.

LEFTOVERS
  On a failed `--verify` the core has already PUBLISHED the archive into the
  output directory, where the runner never learns its name — a plaintext,
  credential-bearing tarball left beside the next run. Whatever a failed call
  leaves in ClawKeep's output directory is removed before the error travels on.
"""

from __future__ import annotations

import contextlib
import fcntl
import json
import logging
import os
import shutil
import tempfile
import unicodedata
from collections.abc import Iterator
from dataclasses import dataclass
from pathlib import Path

from . import crypto, openclaw, sqlite_recovery, token
from .config import Config
from .openclaw import (
    FAILURE_DUPLICATE,
    FAILURE_SQLITE,
    FAILURE_SYMLINK,
    FAILURE_VANISHED,
    Archive,
    BackupPlan,
    Failure,
    OpenclawError,
)

log = logging.getLogger(__name__)

#: Where detached links are written down, inside ClawKeep's own data dir.
JOURNAL_NAME = "detached-links.json"
#: Held for the whole detach → build → put-back window. Nothing else stops a
#: scheduled run and a "Back up now" from overlapping, and one run's put-back
#: must not land in the middle of the other's build.
LOCK_NAME = "archive.lock"
#: Where a database is copied before its indexes are rebuilt.
SQLITE_RECOVERY_DIRNAME = "sqlite-recovery"
#: At most this many databases are repaired in one run.
MAX_SQLITE_REPAIRS = 5
#: The legacy runtime-dependency cache older cores staged inside the state dir.
LEGACY_RUNTIME_DEPS_DIRNAME = "plugin-runtime-deps"
#: `skipped[].reason` values whose trees the archiver does not walk.
_UNWALKED_REASONS = frozenset({"regenerable", "private"})


def _inside(path: str, root: str) -> bool:
    return path == root or path.startswith(root.rstrip("/") + "/")


# ── links ────────────────────────────────────────────────────────────────────

@dataclass(frozen=True)
class RefusedLink:
    """A symlink `openclaw backup create` would refuse to carry."""

    path: str    # the link itself, on disk
    target: str  # its text, never resolved into a walk
    #: Which omission rule covers it (:func:`managed_rule`); "" when none does.
    rule: str = ""

    @property
    def managed(self) -> bool:
        return bool(self.rule)


def _is_volatile_link(path: str, state_dir: str | None) -> bool:
    """The archiver's own skip list, for the links it would never look at
    (`backup-volatile-filter.ts`): sockets, pid and tmp files under the state
    dir, Chromium's singleton links, the skills sandbox and the UI cache."""
    if state_dir is None or not _inside(path, state_dir):
        return False
    rel = os.path.relpath(path, state_dir).split(os.sep)
    if os.path.splitext(path)[1].lower() in (".sock", ".pid", ".tmp"):
        return True
    if len(rel) == 4 and rel[0] == "browser" and rel[2] == "user-data" and rel[3] in (
        "SingletonCookie", "SingletonLock", "SingletonSocket",
    ):
        return True
    return rel[:2] in (["sandbox", "skills-workspaces"], ["cache", "control-ui-assets"])


def _link_refused(path: str, target: str, roots: list[str]) -> bool:
    """Would the archiver refuse this link? Its two rules, in its order: an
    absolute target is rewritten to a relative one only when the target's REAL
    path is inside a declared asset; a relative one must land inside one."""
    if "\\" in target:
        return True
    if os.path.isabs(target):
        try:
            real = os.path.realpath(target, strict=True)
        except OSError:
            return True
        return not any(_inside(real, root) for root in roots)
    landed = os.path.normpath(os.path.join(os.path.dirname(path), target))
    return not any(_inside(landed, root) for root in roots)


RULE_PACKAGES = "package-manager output"
RULE_PLUGIN = "OpenClaw plugin link"
RULE_CACHE = "cache"
RULE_STALE_LOCK = "stale browser lock"


def managed_rule(path: str, asset_root: str, state_dir: str | None) -> str:
    """The explicit omission rule for a link the archiver would refuse — see
    the module docstring. Returns the rule's name, or "" for a link that is
    not the output of a tool that regenerates it."""
    name = os.path.basename(path)
    parents = [p for p in os.path.relpath(os.path.dirname(path), asset_root).split(os.sep)
               if p not in ("", ".", "..")]
    legacy = os.path.join(state_dir, LEGACY_RUNTIME_DEPS_DIRNAME) if state_dir else None
    if legacy is not None and _inside(path, legacy):
        return RULE_PLUGIN
    if parents and parents[-1] == "plugin-skills":
        return RULE_PLUGIN
    if name == "node_modules" or "node_modules" in parents:
        return RULE_PACKAGES
    if any(parents[i] == "pnpm" and parents[i + 1] == "store" for i in range(len(parents) - 1)):
        return RULE_PACKAGES
    if ".cache" in parents:
        return RULE_CACHE
    if name == "SingletonSocket" and not os.path.exists(path):
        return RULE_STALE_LOCK
    return ""


def find_refused_links(plan: BackupPlan) -> list[RefusedLink]:
    """Every symlink in the planned assets the archiver would refuse, sorted.

    Walks with `os.scandir` and never follows a link. Trees the plan says the
    archiver will not walk (`regenerable`, `private`) are not walked here.
    """
    roots = [asset.source_path for asset in plan.assets]
    unwalked = [src for _, src, reason in plan.skipped if reason in _UNWALKED_REASONS]
    state_dir = next((a.source_path for a in plan.assets if a.kind == "state"), None)
    found: dict[str, RefusedLink] = {}

    def consider(path: str, asset_root: str) -> None:
        if path in found or _is_volatile_link(path, state_dir):
            return
        try:
            target = os.readlink(path)
        except OSError:
            return
        if _link_refused(path, target, roots):
            found[path] = RefusedLink(path, target, managed_rule(path, asset_root, state_dir))

    for asset in plan.assets:
        top = asset.source_path
        if os.path.islink(top):
            consider(top, os.path.dirname(top))
            continue
        stack = [top]
        while stack:
            directory = stack.pop()
            try:
                with os.scandir(directory) as it:
                    entries = sorted(it, key=lambda e: e.name)
            except OSError:
                # Gone, or unreadable: the archiver reports that itself.
                continue
            for entry in entries:
                if any(_inside(entry.path, skip) for skip in unwalked):
                    continue
                try:
                    if entry.is_symlink():
                        consider(entry.path, top)
                    elif entry.is_dir(follow_symlinks=False):
                        stack.append(entry.path)
                except OSError:
                    continue
    return [found[p] for p in sorted(found)]


def _journal_entries(journal: Path) -> list[dict[str, str]]:
    try:
        raw = json.loads(journal.read_text(encoding="utf-8"))
    except FileNotFoundError:
        return []
    except (OSError, ValueError) as e:
        log.warning(
            "detached-link journal %s is unreadable, leaving it for a person: %s", journal, e,
        )
        return []
    entries = raw.get("links") if isinstance(raw, dict) else None
    good: list[dict[str, str]] = []
    for entry in entries if isinstance(entries, list) else []:
        if not isinstance(entry, dict):
            continue
        path, target = entry.get("path"), entry.get("target")
        # Only an absolute, normalised link path is ever recreated: the journal
        # is ClawKeep's own file, and a garbled one must not become a symlink
        # planted somewhere relative to whatever the cwd is.
        if (isinstance(path, str) and isinstance(target, str) and target
                and os.path.isabs(path) and os.path.normpath(path) == path):
            good.append({"path": path, "target": target})
    return good


def _write_journal(journal: Path, entries: list[dict[str, str]]) -> None:
    if not entries:
        journal.unlink(missing_ok=True)
        return
    journal.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=str(journal.parent), prefix=".detached-links.", suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            json.dump({"links": entries}, fh, indent=2)
            fh.flush()
            os.fsync(fh.fileno())
        os.chmod(tmp, 0o600)
        os.replace(tmp, journal)
    except BaseException:
        Path(tmp).unlink(missing_ok=True)
        raise


def detach_links(links: list[RefusedLink], journal: Path) -> list[RefusedLink]:
    """Take the MANAGED links out of the tree for the archive build. The
    journal is written before the first unlink, so a crash at any point leaves
    every detached link recoverable."""
    managed = [link for link in links if link.managed]
    if not managed:
        return []
    pending = _journal_entries(journal)
    known = {entry["path"] for entry in pending}
    fresh = [link for link in managed if link.path not in known]

    def entries(links: list[RefusedLink]) -> list[dict[str, str]]:
        return pending + [{"path": link.path, "target": link.target} for link in links]

    _write_journal(journal, entries(fresh))
    detached: list[RefusedLink] = []
    for link in fresh:
        try:
            # Still the link that was scanned — never unlink something that
            # changed underneath the scan.
            if os.readlink(link.path) != link.target:
                continue
            os.unlink(link.path)
        except OSError as e:
            log.warning("could not set aside managed link %s: %s", link.path, e)
            continue
        detached.append(link)
    _write_journal(journal, entries(detached))
    if detached:
        log.info(
            "omitting %d managed link(s) from this archive; they are put back when it is built: %s",
            len(detached),
            ", ".join(f"{link.path} -> {link.target} ({link.rule})" for link in detached),
        )
    return detached


def reattach_links(journal: Path) -> list[str]:
    """Put back every link the journal names. A path something else has
    recreated meanwhile is left as it is; one whose directory is gone is
    dropped from the journal with a warning. Returns the paths restored."""
    entries = _journal_entries(journal)
    if not entries:
        journal.unlink(missing_ok=True)
        return []
    restored: list[str] = []
    remaining: list[dict[str, str]] = []
    for entry in entries:
        path, target = entry["path"], entry["target"]
        if os.path.lexists(path):
            continue
        if not os.path.isdir(os.path.dirname(path)):
            log.warning("not restoring link %s -> %s: its directory is gone", path, target)
            continue
        try:
            os.symlink(target, path)
        except OSError as e:
            log.warning(
                "could not restore link %s -> %s (kept in %s): %s", path, target, journal, e,
            )
            remaining.append(entry)
            continue
        restored.append(path)
    _write_journal(journal, remaining)
    return restored


# ── duplicate logical paths ──────────────────────────────────────────────────

def _portable(archive_path: str) -> str:
    """The archiver's `resolvePortableArchivePathKey`: NFC, lower-cased."""
    return unicodedata.normalize("NFC", archive_path).lower()


def assert_no_duplicate_paths(plan: BackupPlan) -> None:
    """Refuse a plan in which two sources would be written to one archive
    path — before a single byte is archived. Deterministic: the first pair in
    archive-path order is the one reported."""
    assets = sorted(plan.assets, key=lambda a: (a.archive_path, a.kind, a.source_path))
    for i, first in enumerate(assets):
        a = first.archive_path.rstrip("/")
        for second in assets[i + 1:]:
            b = second.archive_path.rstrip("/")
            if a == b:
                why = "both would be written to"
            elif _inside(b, a) or _inside(a, b):
                why = "one would be written inside the other at"
            elif _portable(a) == _portable(b):
                why = "their archive paths differ only in letter case or Unicode form at"
            else:
                continue
            raise OpenclawError(
                "refusing to build the backup: two sources claim the same place in the archive — "
                f"{first.kind} {first.source_path!r} and {second.kind} {second.source_path!r}; "
                f"{why} {a!r}. Nothing was archived; move or remove one of them and the next "
                "backup will run",
                failure=Failure(FAILURE_DUPLICATE, (first.source_path, second.source_path)),
            )


def _owners(source: str, plan: BackupPlan | None) -> str:
    if plan is None:
        return ""
    owners = [f"{a.kind} {a.source_path!r}" for a in plan.assets if _inside(source, a.source_path)]
    return f" (inside {', '.join(owners)})" if owners else ""


# ── the call itself ──────────────────────────────────────────────────────────

def _plan(cfg: Config) -> BackupPlan | None:
    """The dry-run for this backup's options, or `None` — the pre-flight is
    best effort and never becomes a reason on its own for a backup to fail."""
    try:
        return openclaw.plan_backup(
            cfg.openclaw.binary,
            include_workspace=cfg.openclaw.include_workspace,
            only_config=cfg.openclaw.only_config,
        )
    except OpenclawError as e:
        log.warning("backup pre-flight skipped — the dry-run did not answer: %s", e)
        return None


def _listing(directory: Path) -> set[str]:
    try:
        return {entry.name for entry in os.scandir(directory)}
    except OSError:
        return set()


def remove_leftovers(directory: Path, before: set[str]) -> list[str]:
    """Remove what a FAILED `backup create` left in ClawKeep's output dir:
    a published archive (plaintext, credential-bearing) and the core's own
    `.openclaw-backup-publish-*` staging. Only names that were not there
    before the call, and only those two shapes."""
    removed: list[str] = []
    try:
        entries = list(os.scandir(directory))
    except OSError:
        return removed
    for entry in entries:
        if entry.name in before:
            continue
        try:
            staging = entry.name.startswith(".openclaw-backup-publish-")
            if entry.is_dir(follow_symlinks=False) and staging:
                shutil.rmtree(entry.path, ignore_errors=True)
            elif entry.is_file(follow_symlinks=False) and ".tar.gz" in entry.name:
                crypto.secure_unlink(Path(entry.path))
            else:
                continue
        except OSError as e:
            log.warning("could not remove backup leftover %s: %s", entry.path, e)
            continue
        removed.append(entry.path)
    if removed:
        log.warning("removed what the failed archive build left behind: %s", ", ".join(removed))
    return removed


def _refine(exc: OpenclawError, plan: BackupPlan | None) -> OpenclawError:
    """Say what the failure was, with the sources named, in one sentence.

    ClawKeep's sentence comes FIRST and the archiver's own text after it: the
    portal heartbeat keeps 500 characters, and the CLI's sentences are long."""
    failure = openclaw.failure_of(exc)
    if failure.kind == FAILURE_VANISHED and plan is not None and failure.paths:
        roots = [a.source_path for a in plan.assets]
        if not any(_inside(failure.paths[0], root) for root in roots):
            # Not a file of the backup — a race is not what this is.
            return OpenclawError(str(exc), failure=Failure(FAILURE_VANISHED, failure.paths))
        return exc
    if failure.kind == FAILURE_SYMLINK and failure.paths:
        entry = failure.paths[0]
        source = openclaw.archive_source_path(entry) or entry
        target = failure.paths[1] if len(failure.paths) > 1 else "(nothing)"
        return OpenclawError(
            f"the symbolic link {source!r} points to {target!r}, outside everything this backup "
            f"contains{_owners(source, plan)}; ClawKeep does not carry or follow a link out of the "
            "backup. Remove the link, or move what it points at inside the backed-up folders, and "
            f"the next backup will run. The archiver said: {exc}",
            failure=Failure(FAILURE_SYMLINK, (source, target)),
        )
    if failure.kind == FAILURE_DUPLICATE and failure.paths:
        sources = [openclaw.archive_source_path(p) or p for p in failure.paths]
        named = " and ".join(f"{s!r}{_owners(s, plan)}" for s in sources)
        return OpenclawError(
            f"two archive entries claim the same path — conflicting source(s): {named}. Nothing "
            "was uploaded; rename or remove one of them and the next backup will run. The "
            f"archiver said: {exc}",
            failure=Failure(FAILURE_DUPLICATE, tuple(sources)),
        )
    return exc


def _sqlite_roots(plan: BackupPlan | None) -> list[str]:
    if plan is None:
        return [openclaw.state_dir()]
    roots = [a.source_path for a in plan.assets if a.kind in ("state", "agent")]
    return roots or [openclaw.state_dir()]


def _damaged(
    exc: OpenclawError, database: str, outcome: sqlite_recovery.Recovery | None,
) -> OpenclawError:
    found = "; ".join(outcome.problems) if outcome and outcome.problems else "see the error above"
    why = (
        outcome.reason if outcome and outcome.reason
        else "it still failed after its indexes were rebuilt"
    )
    kept = (
        f" A copy of it as found is kept at {str(outcome.preserved_copy)!r}."
        if outcome and outcome.preserved_copy else ""
    )
    return OpenclawError(
        f"the database {database!r} fails its SQLite integrity check ({found}); {why}. ClawKeep "
        "did not back it up, skip it, or copy it byte for byte, because a backup of a database "
        f"that fails that check can carry damaged or deleted data.{kept} Snapshots already in "
        "the cloud are untouched; the database needs repairing before this box can be backed up "
        f"again — ClawBox support can help. The archiver said: {exc}",
        failure=Failure(FAILURE_SQLITE, (database,)),
    )


@contextlib.contextmanager
def exclusive(lock: Path) -> Iterator[None]:
    """One archive build at a time on this box; a second run waits its turn."""
    lock.parent.mkdir(parents=True, exist_ok=True)
    fd = os.open(lock, os.O_RDWR | os.O_CREAT, 0o600)
    try:
        try:
            fcntl.flock(fd, fcntl.LOCK_EX | fcntl.LOCK_NB)
        except BlockingIOError:
            log.info("another backup is building its archive; waiting for it to finish")
            fcntl.flock(fd, fcntl.LOCK_EX)
        yield
    finally:
        os.close(fd)


def create_archive(cfg: Config, *, output_dir: Path) -> Archive:
    """`openclaw.create_archive`, with ClawKeep's pre-flight and recovery
    around it. Raises `OpenclawError` whose `failure` says what went wrong."""
    with exclusive(token.data_dir() / LOCK_NAME):
        return _create_archive(cfg, output_dir=output_dir)


def _create_archive(cfg: Config, *, output_dir: Path) -> Archive:
    journal = token.data_dir() / JOURNAL_NAME
    restored = reattach_links(journal)
    if restored:
        log.warning("put back %d package link(s) an interrupted backup had set aside: %s",
                    len(restored), ", ".join(restored))

    plan = _plan(cfg)
    if plan is not None:
        assert_no_duplicate_paths(plan)
    links = find_refused_links(plan) if plan is not None else []
    for link in links:
        if not link.managed:
            log.warning(
                "the archiver will refuse the symbolic link %s -> %s: it points outside the "
                "backup and is not a package-manager link ClawKeep may omit",
                link.path, link.target,
            )

    output_dir.mkdir(parents=True, exist_ok=True)
    detach_links(links, journal)
    try:
        return _create_with_sqlite_recovery(cfg, output_dir, plan)
    finally:
        reattach_links(journal)


def _create_with_sqlite_recovery(cfg: Config, output_dir: Path, plan: BackupPlan | None) -> Archive:
    attempted: set[str] = set()
    while True:
        before = _listing(output_dir)
        try:
            return openclaw.create_archive(
                cfg.openclaw.binary,
                output_dir=output_dir,
                include_workspace=cfg.openclaw.include_workspace,
                only_config=cfg.openclaw.only_config,
                verify=cfg.openclaw.verify,
            )
        except OpenclawError as exc:
            remove_leftovers(output_dir, before)
            failure = openclaw.failure_of(exc)
            if failure.kind != FAILURE_SQLITE or not failure.paths:
                raise _refine(exc, plan) from exc
            database = failure.paths[0]
            if database in attempted or len(attempted) >= MAX_SQLITE_REPAIRS:
                raise _damaged(exc, database, None) from exc
            attempted.add(database)
            outcome = sqlite_recovery.recover(
                Path(database),
                allowed_roots=_sqlite_roots(plan),
                recovery_dir=token.data_dir() / SQLITE_RECOVERY_DIRNAME,
            )
            if outcome.status == sqlite_recovery.RECOVERY_REFUSED:
                log.error("not repairing %s: %s (%s)", database, outcome.reason,
                          "; ".join(outcome.problems))
                raise _damaged(exc, database, outcome) from exc
            # Repaired, or healthy by the time it was looked at (it was being
            # written): the core's own gate judges it again on this attempt.
            repaired = outcome.status == sqlite_recovery.RECOVERY_REPAIRED
            log.warning(
                "retrying the archive after %s %s", database,
                "had its indexes rebuilt" if repaired
                else "passed its integrity check on a second look",
            )
