import { NextResponse } from "next/server";
import { kvGet } from "@/lib/kv-store";
import { getMascotPhrases } from "@/lib/mascot-phrases-server";

export const dynamic = "force-dynamic";

// Must match MASCOT_LINES_KEY in ChatPopup.tsx — short snippets the chat
// auto-captures from assistant replies for the "the crab quotes you back"
// running gag.
const KV_CONVO_KEY = "clawbox-mascot-convo-lines";

/**
 * GET /setup-api/mascot-lines
 *
 * Returns the full categorized phrase set for the mascot, plus the
 * conversation snippets the chat has been collecting through the day.
 *
 * The categorized set is generated by the local LLM via Ollama in the
 * user's selected language, refreshed weekly with daily top-ups so the
 * crab's vocabulary evolves with the user's work. If generation hasn't
 * succeeded yet (fresh device, Ollama not ready), the inspiration
 * fallbacks ship instead so the mascot still has something to say.
 *
 * Response (back-compat with the old shape — `lines` is still present):
 * {
 *   lines: string[]              // legacy: conversation snippets (sass)
 *   date?: string                // legacy: snippet capture date
 *   phrases: MascotPhraseSet     // categorized generated phrases
 *   meta: { generated, language, lastFullRegen, lastTopUp }
 * }
 */
export async function GET() {
  const { phrases, meta } = getMascotPhrases();

  // Conversation snippets (existing behavior — preserved for back-compat).
  // The KV blob is written by ChatPopup, but the file is human-editable, so
  // validate the shape before assigning — a corrupted entry shouldn't crash
  // the mascot route or feed bad data into the phrase generator.
  const raw = kvGet(KV_CONVO_KEY);
  let lines: string[] = [];
  let date: string | undefined;
  if (raw) {
    try {
      const data = JSON.parse(raw) as unknown;
      if (data && typeof data === "object") {
        const obj = data as Record<string, unknown>;
        if (Array.isArray(obj.lines) && obj.lines.every((item) => typeof item === "string")) {
          lines = obj.lines as string[];
        }
        if (typeof obj.date === "string") {
          date = obj.date;
        }
      }
    } catch { /* ignore */ }
  }

  return NextResponse.json({ lines, date, phrases, meta });
}
